bind: 127.0.0.1:5000

oplog: mongodb://localhost:27017/paxp2.oplog
#stats: redis://localhost:6379/0

resources:
  dsp:
  - id: dsp-0
    name: DSP-0
    burl: http://localhost:8800/bid/
  - id: dsp-1
    name: DSP-1
    burl: http://localhost:8801/bid/
  - id: dsp-2
    name: DSP-2
    burl: http://localhost:8802/bid/

logging:
  formatters:
    default:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      datefmt: '%FT%T'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: default
      level: INFO
      filename: paxp2.log
      maxBytes: 1000000
      backupCount: 3
  loggers:
    requests:
      level: ERROR
    werkzeug:
      level: INFO
  root:
      handlers: [console, file]
      level: DEBUG

